/**
 * Keyword-based emoji mapping for Mercadona subcategories.
 * Rules are checked in order — first match wins (specific before general).
 */
const RULES: [string, string][] = [
  // ── Bonpreu / Carrefour / bonÀrea ─────────────────────────────
  // Va PRIMERO: términos específicos de estos catálogos que deben ganar a las
  // reglas generales de abajo (p.ej. "sopas/caldos" antes que la 'crema '
  // cosmética; "aceites de motor" antes que 'aceite' de oliva).

  // Comida que chocaría con reglas generales o que faltaba
  ['sopa',          '🍲'],
  ['caldo',         '🍲'],
  ['gazpacho',      '🍲'],
  ['puré',          '🍲'],
  ['canelon',       '🍝'],
  ['lasaña',        '🍝'],
  ['sushi',         '🍣'],
  ['allioli',       '🧄'],
  ['bombon',        '🍫'],
  ['horchata',      '🥛'],
  ['batidos',       '🥛'],
  ['cava',          '🥂'],
  ['espumoso',      '🥂'],
  ['brut',          '🥂'],
  ['brandy',        '🥃'],
  ['anís',          '🥃'],
  ['pacharán',      '🥃'],
  ['panceta',       '🥓'],
  ['caracol',       '🐌'],
  ['aves',          '🍗'],

  // Bazar / no alimentación (sobre todo bonÀrea)
  ['aceite de motor', '🛢️'],
  ['aceites de motor','🛢️'],
  ['anticongelante',  '🛢️'],
  ['neumático',     '🛞'],
  ['bujía',         '🔧'],
  ['calcetin',      '🧦'],
  ['camiseta',      '👕'],
  ['braguita',      '🩲'],
  ['boxer',         '🩲'],
  ['calzoncillo',   '🩲'],
  ['abrigo',        '🧥'],
  ['jersey',        '🧥'],
  ['botas',         '👢'],
  ['zapato',        '👟'],
  ['zapatilla',     '👟'],
  ['calzado',       '👟'],
  ['casco',         '⛑️'],
  ['gorro',         '🧢'],
  ['guante',        '🧤'],
  ['bombilla',      '💡'],
  ['pilas',         '🔋'],
  ['batería de cocina', '🍳'],
  ['batería',       '🔋'],
  ['cargador',      '🔌'],
  ['alargador',     '🔌'],
  ['enchufe',       '🔌'],
  ['herramienta',   '🛠️'],
  ['alicate',       '🔧'],
  ['destornillador','🪛'],
  ['tornillo',      '🔩'],
  ['broca',         '🪛'],
  ['brocha',        '🖌️'],
  ['pincel',        '🖌️'],
  ['barniz',        '🪵'],
  ['pintura',       '🎨'],
  ['bolígrafo',     '🖊️'],
  ['cuaderno',      '📒'],
  ['libreta',       '📒'],
  ['archivador',    '🗂️'],
  ['carpeta',       '🗂️'],
  ['agenda',        '📔'],
  ['libro',         '📚'],
  ['juguete',       '🧸'],
  ['peluche',       '🧸'],
  ['almohada',      '🛏️'],
  ['sábana',        '🛏️'],
  ['edredon',       '🛏️'],
  ['colchon',       '🛏️'],
  ['menaje',        '🍽️'],
  ['sartén',        '🍳'],
  ['sarten',        '🍳'],
  ['cacerola',      '🍳'],
  ['cuchillo',      '🔪'],
  ['cafetera',      '☕'],
  ['aspirador',     '🧹'],
  ['ventilador',    '🌀'],
  ['radiador',      '🔥'],
  ['abono',         '🌱'],
  ['fertilizante',  '🌱'],
  ['semilla',       '🌱'],
  ['maceta',        '🪴'],
  ['manguera',      '💦'],
  ['pienso',        '🦴'],
  ['bebedero',      '🐾'],
  ['comedero',      '🐾'],
  ['antiparasitario','🐾'],

  // Comida y cuidado personal comunes que faltaban (Bonpreu/Carrefour)
  ['carnicer',      '🥩'],
  ['carne',         '🥩'],
  ['charcuter',     '🥓'],
  ['pescader',      '🐟'],
  ['lácteo',        '🥛'],
  ['refresco',      '🥤'],
  ['frescos',       '🥬'],
  ['desayuno',      '🥣'],
  ['repostería',    '🧁'],
  ['dulce',         '🍬'],
  ['hielo',         '🧊'],
  ['sin alcohol',   '🥤'],
  ['alcohol',       '🥃'],
  ['energétic',     '⚡'],
  ['comidas del mundo', '🌍'],
  ['rebozado',      '🍤'],
  ['platos preparados', '🍱'],
  ['comida prepar', '🍱'],
  ['freidora',      '🍳'],
  ['air fryer',     '🍳'],
  ['nutrición',     '💪'],
  ['suplemento',    '💊'],
  ['cosmética',     '💄'],
  ['capilar',       '💇'],
  ['cabello',       '💇'],
  ['depila',        '🪒'],
  ['solar',         '🧴'],
  ['embarazo',      '🤰'],
  ['lactancia',     '🍼'],
  ['puericultura',  '🍼'],
  ['botiquín',      '🩹'],
  ['pizza',         '🍕'],
  ['limpieza',      '🧹'],
  ['limpia',        '🧹'],
  ['manos y pies',  '💅'],
  ['corporal',      '🧴'],
  ['sexual',        '❤️'],

  // ── Frutas ────────────────────────────────────────────────────
  ['plátano',       '🍌'],
  ['fresa',         '🍓'],
  ['frambuesa',     '🍓'],
  ['arándano',      '🫐'],
  ['cereza',        '🍒'],
  ['melocotón',     '🍑'],
  ['albaricoque',   '🍑'],
  ['ciruela',       '🍑'],
  ['sandía',        '🍉'],
  ['melón',         '🍈'],
  ['uva',           '🍇'],
  ['piña',          '🍍'],
  ['mango',         '🥭'],
  ['aguacate',      '🥑'],
  ['kiwi',          '🥝'],
  ['cítrico',       '🍊'],
  ['naranja',       '🍊'],
  ['limón',         '🍋'],
  ['pomelo',        '🍋'],
  ['mandarina',     '🍊'],
  ['pera',          '🍐'],
  ['manzana',       '🍎'],
  ['fruta',         '🍎'],
  ['frutos rojos',  '🍓'],
  ['frutos tropic', '🍍'],

  // ── Verduras y hortalizas ─────────────────────────────────────
  ['ensalada',      '🥗'],
  ['brote',         '🌱'],
  ['espinaca',      '🥬'],
  ['lechuga',       '🥬'],
  ['col ',          '🥦'],
  ['brócoli',       '🥦'],
  ['coliflor',      '🥦'],
  ['alcachofa',     '🌿'],
  ['espárrago',     '🌿'],
  ['pimiento',      '🫑'],
  ['tomate',        '🍅'],
  ['pepino',        '🥒'],
  ['calabacín',     '🥒'],
  ['berenjena',     '🍆'],
  ['cebolla',       '🧅'],
  ['ajo',           '🧄'],
  ['patata',        '🥔'],
  ['zanahoria',     '🥕'],
  ['seta',          '🍄'],
  ['champiñón',     '🍄'],
  ['hierba aromát', '🌿'],
  ['hierbas',       '🌿'],
  ['verdura',       '🥦'],
  ['hortaliza',     '🥦'],

  // ── Carne ─────────────────────────────────────────────────────
  ['hamburguesa',   '🍔'],
  ['albóndiga',     '🍖'],
  ['preparado cárn','🍖'],
  ['pollo',         '🍗'],
  ['pavo',          '🍗'],
  ['cerdo',         '🥩'],
  ['ternera',       '🥩'],
  ['cordero',       '🥩'],
  ['conejo',        '🐰'],
  ['caza',          '🦌'],

  // ── Charcutería ───────────────────────────────────────────────
  ['jamón',         '🍖'],
  ['chorizo',       '🌭'],
  ['salchicha',     '🌭'],
  ['mortadela',     '🍖'],
  ['fuet',          '🌭'],
  ['lomo',          '🥓'],
  ['bacon',         '🥓'],
  ['embutido',      '🥓'],
  ['fiambre',       '🥓'],
  ['paté',          '🫙'],
  ['foie',          '🫙'],

  // ── Pescado y marisco ─────────────────────────────────────────
  ['salmón',        '🐟'],
  ['ahumado',       '🐟'],
  ['bacalao',       '🐟'],
  ['merluza',       '🐟'],
  ['dorada',        '🐟'],
  ['atún',          '🐟'],
  ['sardina',       '🐟'],
  ['anchoa',        '🐟'],
  ['boquerón',      '🐟'],
  ['pulpo',         '🐙'],
  ['calamar',       '🦑'],
  ['sepia',         '🦑'],
  ['mejillón',      '🦪'],
  ['almeja',        '🦪'],
  ['berberecho',    '🦪'],
  ['gamba',         '🦐'],
  ['langostino',    '🦐'],
  ['cangrejo',      '🦀'],
  ['marisco',       '🦐'],
  ['pescado',       '🐟'],

  // ── Lácteos ───────────────────────────────────────────────────
  ['mantequilla',   '🧈'],
  ['margarina',     '🧈'],
  ['queso',         '🧀'],
  ['yogur',         '🥛'],
  ['kéfir',         '🥛'],
  ['nata',          '🥛'],
  ['leche',         '🥛'],
  ['bebida vegetal','🥛'],
  ['huevo',         '🥚'],

  // ── Panadería y bollería ──────────────────────────────────────
  ['croissant',     '🥐'],
  ['brioche',       '🥐'],
  ['bollería',      '🥐'],
  ['bollo',         '🥐'],
  ['donut',         '🍩'],
  ['magdalena',     '🧁'],
  ['muffin',        '🧁'],
  ['bizcocho',      '🍰'],
  ['tarta',         '🎂'],
  ['pastel',        '🍰'],
  ['galleta',       '🍪'],
  ['pan de molde',  '🍞'],
  ['tostada',       '🍞'],
  ['pan ',          '🥖'],
  ['baguette',      '🥖'],
  ['masa',          '🥖'],
  ['panadería',     '🥖'],

  // ── Bebidas (específico → general) ───────────────────────────
  ['isotónico',     '⚡'],
  ['energético',    '⚡'],
  ['cerveza',       '🍺'],
  ['sidra',         '🥂'],
  ['cava',          '🥂'],
  ['champán',       '🥂'],
  ['vino blanco',   '🍾'],
  ['vino rosado',   '🍾'],
  ['vino',          '🍷'],
  ['whisky',        '🥃'],
  ['ron ',          '🥃'],
  ['ginebra',       '🥃'],
  ['vodka',         '🥃'],
  ['licor',         '🥃'],
  ['destilado',     '🥃'],
  ['tónica',        '🍸'],
  ['bitter',        '🍸'],
  ['cola',          '🥤'],
  ['té ',           '🍵'],
  ['sin gas',       '🫧'],
  ['zumo',          '🧃'],
  ['néctar',        '🧃'],
  ['agua',          '💧'],
  ['refresco',      '🥤'],
  ['bebida',        '🥤'],

  // ── Congelados ────────────────────────────────────────────────
  ['helado',        '🍦'],
  ['sorbete',       '🍧'],
  ['pizza congelada','🍕'],
  ['croqueta',      '🍱'],
  ['precocinado',   '🍱'],
  ['verdura congelada','🧊'],
  ['pescado congelado','🧊'],
  ['congelado',     '🧊'],

  // ── Conservas ─────────────────────────────────────────────────
  ['aceituna',      '🫒'],
  ['pepinillo',     '🥒'],
  ['encurtido',     '🥒'],
  ['legumbre',      '🫘'],
  ['lenteja',       '🫘'],
  ['garbanzo',      '🫘'],
  ['judía',         '🫘'],
  ['alubia',        '🫘'],
  ['conserva',      '🥫'],

  // ── Pasta, arroz y cereales ───────────────────────────────────
  ['espagueti',     '🍝'],
  ['macarrón',      '🍝'],
  ['tallarín',      '🍝'],
  ['pasta',         '🍝'],
  ['arroz',         '🍚'],
  ['avena',         '🥣'],
  ['cereal',        '🥣'],
  ['granola',       '🥣'],
  ['muesli',        '🥣'],

  // ── Aceites, salsas y especias ────────────────────────────────
  ['aceite',        '🫒'],
  ['vinagre',       '🫒'],
  ['especias',      '🌿'],
  ['pimienta',      '🌿'],
  ['curry',         '🌿'],
  ['mayonesa',      '🥫'],
  ['ketchup',       '🥫'],
  ['mostaza',       '🥫'],
  ['salsas',        '🫙'],

  // ── Desayuno y dulces ─────────────────────────────────────────
  // (chocolate va ANTES de la regla 'cola' que está en bebidas)
  ['chocolate',     '🍫'],
  ['nocilla',       '🍫'],
  ['crema de cacat','🍫'],
  ['colacao',       '☕'],
  ['cacao',         '☕'],
  ['café',          '☕'],
  ['infusión',      '🍵'],
  ['manzanilla',    '🍵'],
  ['mermelada',     '🍯'],
  ['miel',          '🍯'],
  ['azúcar',        '🍬'],
  ['edulcorante',   '🍬'],
  ['chicle',        '🫧'],
  ['caramelo',      '🍭'],
  ['golosina',      '🍭'],

  // ── Snacks y aperitivos ───────────────────────────────────────
  ['fruto seco',    '🥜'],
  ['cacahuete',     '🥜'],
  ['almendra',      '🥜'],
  ['nuez',          '🥜'],
  ['pistacho',      '🥜'],
  ['palomita',      '🍿'],
  ['patatas fritas','🍟'],
  ['chip',          '🍟'],
  ['cracker',       '🫙'],
  ['aperitivo',     '🥨'],
  ['snack',         '🥨'],

  // ── Higiene y cuidado personal ────────────────────────────────
  ['pasta de dientes','🦷'],
  ['cepillo dental', '🦷'],
  ['hilo dental',   '🦷'],
  ['champú',        '🧴'],
  ['acondicionador','🧴'],
  ['gel de ducha',  '🧴'],
  ['gel ',          '🧴'],
  ['jabón',         '🧼'],
  ['desodorante',   '🧴'],
  ['crema hidrat',  '🧴'],
  ['crema solar',   '🧴'],
  ['crema ',        '🧴'],
  ['maquillaje',    '💄'],
  ['colorete',      '💄'],
  ['máscara',       '💄'],
  ['perfume',       '🌸'],
  ['colonia',       '🌸'],
  ['compresas',     '🩸'],
  ['tampón',        '🩸'],
  ['cuchilla',      '🪒'],
  ['afeitado',      '🪒'],
  ['pañuelo',       '🤧'],
  ['algodón',       '🩹'],

  // ── Limpieza del hogar ────────────────────────────────────────
  ['papel higiénico','🧻'],
  ['papel de cocina','🧻'],
  ['servilleta',    '🧻'],
  ['papel ',        '🧻'],
  ['lavavajillas',  '🍽️'],
  ['detergente',    '🧺'],
  ['suavizante',    '🧺'],
  ['quitamanchas',  '🧺'],
  ['lejía',         '🧹'],
  ['limpiador',     '🧹'],
  ['friegasuelos',  '🧹'],
  ['bayeta',        '🧹'],
  ['estropajo',     '🧹'],
  ['escoba',        '🧹'],
  ['bolsa de basura','🗑️'],
  ['basura',        '🗑️'],
  ['insecticida',   '🐛'],
  ['ambientador',   '🌸'],

  // ── Higiene (general, cubre también bebés) ────────────────────
  ['higiene',       '🧴'],

  // ── Mascotas ──────────────────────────────────────────────────
  ['perro',         '🐶'],
  ['gato',          '🐱'],
  ['mascota',       '🐾'],

  // ── Bebés ─────────────────────────────────────────────────────
  ['biberón',       '🍼'],
  ['chupete',       '🍼'],
  ['potito',        '🍼'],
  ['papilla',       '🍼'],
  ['alimentación inf', '🍼'],
  ['pañal',         '🧻'],
  ['toallita',      '🧻'],
  ['bebé',          '👶'],
  ['infantil',      '👶'],

  // ── Dia / Consum: N2 que se quedaban con el carrito por defecto ────
  // (los nombres de estos catálogos no encajaban en las reglas de arriba)
  ['vacuno',        '🥩'],
  ['despiece',      '🥩'],
  ['empanado',      '🍤'],
  ['surimi',        '🦀'],
  ['fideo',         '🍜'],
  ['noodle',        '🍜'],
  ['quinoa',        '🌾'],
  ['couscous',      '🌾'],
  ['harina',        '🌾'],
  ['levadura',      '🌾'],
  ['frutos seco',   '🥜'],
  ['barbacoa',      '🍖'],
  ['comida asiát',  '🍜'],
  ['mexicana',      '🌮'],
  ['comida tradicional', '🍲'],
  ['hummus',        '🧆'],
  ['guacamole',     '🥑'],
  ['limonada',      '🍋'],
  ['smoothie',      '🥤'],
  ['sazonador',     '🧂'],
  ['tortita',       '🥞'],
  ['tortillas de trigo', '🫓'],   // wraps/fajitas, no tortilla de patata
  ['pan de pita',   '🫓'],
  ['tortilla',      '🍳'],        // tortilla de patata / francesa
  ['gelatina',      '🍮'],
  ['postres tradicion', '🍮'],
  ['preparados para postres', '🧁'],
  ['platos sin gluten', '🍽️'],
  ['listos para comer', '🍱'],
  ['listo para comer',  '🍱'],
  ['preparados refriger','🍱'],
  // Consum
  ['cuidado personal', '🧴'],
  ['desechable',    '🍽️'],
  ['despensa',      '🥫'],
  ['jardín',        '🪴'],
  ['jardin',        '🪴'],
  ['promocional',   '🏷️'],
  ['velas',         '🕯️'],
  ['bazar',         '🛍️'],

  // ── CATALÀ (Mercadona con lang=ca + Bonpreu/bonÀrea, nativos) ──────
  // Se evalúan DESPUÉS de las reglas en castellano. Solo términos catalanes
  // distintivos (≥4 letras o con acento) para no falsear nombres en castellano.
  // Lo no cubierto cae al emoji de su categoría padre (fallback), no al 🛒.
  // Fruites
  ['plàtan',        '🍌'],
  ['maduixa',       '🍓'],
  ['gerd',          '🍓'],
  ['nabiu',         '🫐'],
  ['cirera',        '🍒'],
  ['préssec',       '🍑'],
  ['albercoc',      '🍑'],
  ['pruna',         '🍑'],
  ['síndria',       '🍉'],
  ['meló',          '🍈'],
  ['raïm',          '🍇'],
  ['pinya',         '🍍'],
  ['alvocat',       '🥑'],
  ['taronja',       '🍊'],
  ['llimona',       '🍋'],
  ['poma',          '🍎'],
  ['fruita',        '🍎'],
  // Verdures i hortalisses
  ['enciam',        '🥬'],
  ['espinac',       '🥬'],
  ['bròquil',       '🥦'],
  ['carxofa',       '🌿'],
  ['espàrrec',      '🌿'],
  ['pebrot',        '🫑'],
  ['tomàquet',      '🍅'],
  ['cogombre',      '🥒'],
  ['carbassó',      '🥒'],
  ['albergínia',    '🍆'],
  ['ceba',          '🧅'],
  ['pastanaga',     '🥕'],
  ['bolet',         '🍄'],
  ['hortalissa',    '🥦'],
  ['verdura',       '🥦'],
  // Carn
  ['hamburgues',    '🍔'],
  ['mandonguilla',  '🍖'],
  ['pollastre',     '🍗'],
  ['gall dindi',    '🍗'],
  ['porc',          '🥩'],
  ['vedella',       '🥩'],
  ['xai',           '🥩'],
  ['conill',        '🐰'],
  // Xarcuteria
  ['pernil',        '🍖'],
  ['cansalada',     '🥓'],
  ['embotit',       '🥓'],
  ['formatge',      '🧀'],
  // Peix i marisc
  ['salmó',         '🐟'],
  ['bacallà',       '🐟'],
  ['lluç',          '🐟'],
  ['orada',         '🐟'],
  ['tonyina',       '🐟'],
  ['seitó',         '🐟'],
  ['sípia',         '🦑'],
  ['musclo',        '🦪'],
  ['cloïssa',       '🦪'],
  ['llagostí',      '🦐'],
  ['cranc',         '🦀'],
  ['marisc',        '🦐'],
  ['peix',          '🐟'],
  // Làctics
  ['mantega',       '🧈'],
  ['iogurt',        '🥛'],
  ['llet',          '🥛'],
  // Fleca i brioixeria
  ['brioix',        '🥐'],
  ['pa de motlle',  '🍞'],
  ['torrada',       '🍞'],
  ['pastís',        '🍰'],
  ['coca',          '🍰'],
  ['galet',         '🍪'],
  ['pa ',           '🥖'],
  ['fleca',         '🥖'],
  // Begudes
  ['cervesa',       '🍺'],
  ['vi negre',      '🍷'],
  ['vi blanc',      '🍾'],
  ['vi rosat',      '🍾'],
  ['tònica',        '🍸'],
  ['bíter',         '🍸'],
  ['aigua',         '💧'],
  ['sucs',          '🧃'],
  ['suc ',          '🧃'],
  ['refresc',       '🥤'],
  ['beguda',        '🥤'],
  // Congelats
  ['gelat',         '🍦'],
  ['congelat',      '🧊'],
  // Conserves i llegums
  ['oliva',         '🫒'],
  ['llentia',       '🫘'],
  ['cigró',         '🫘'],
  ['mongeta',       '🫘'],
  ['llegum',        '🫘'],
  ['conserva',      '🥫'],
  // Pasta, arròs, cereals
  ['arròs',         '🍚'],
  ['civada',        '🥣'],
  ['cereal',        '🥣'],
  // Oli, vinagre i salses
  ['vinagre',       '🫒'],
  ['espècies',      '🌿'],
  ['maionesa',      '🥫'],
  ['salses',        '🫙'],
  ['oli ',          '🫒'],
  // Esmorzar i dolços
  ['xocolata',      '🍫'],
  ['cacau',         '☕'],
  ['cafè',          '☕'],
  ['infusió',       '🍵'],
  ['melmelada',     '🍯'],
  ['sucre',         '🍬'],
  ['llaminadura',   '🍭'],
  ['caramel',       '🍭'],
  // Snacks
  ['fruita seca',   '🥜'],
  ['cacauet',       '🥜'],
  ['ametlla',       '🥜'],
  ['avellana',      '🥜'],
  ['crispetes',     '🍿'],
  ['patates fregides','🍟'],
  ['aperitiu',      '🥨'],
  // Higiene
  ['pasta de dents','🦷'],
  ['raspall de dents','🦷'],
  ['xampú',         '🧴'],
  ['sabó',          '🧼'],
  ['desodorant',    '🧴'],
  ['maquilla',      '💄'],
  ['compresa',      '🩸'],
  ['afaitat',       '🪒'],
  // Neteja
  ['paper higiènic','🧻'],
  ['paper de cuina','🧻'],
  ['tovalló',       '🧻'],
  ['rentavaixelles','🍽️'],
  ['suavitzant',    '🧺'],
  ['lleixiu',       '🧹'],
  ['netejador',     '🧹'],
  ['fregall',       '🧹'],
  ['escombra',      '🧹'],
  // Mascotes
  ['pinso',         '🦴'],
  ['gos',           '🐶'],
  ['mascot',        '🐾'],
  // Nadó
  ['biberó',        '🍼'],
  ['bolquer',       '🧻'],
  ['nadó',          '👶'],
];

export function getSubcategoryEmoji(name: string, fallback: string): string {
  const lower = name.toLowerCase();
  for (const [keyword, emoji] of RULES) {
    if (lower.includes(keyword)) return emoji;
  }
  return fallback;
}
