-- OBSOLETO: no ejecutar.
--
-- El modelo de owner_id único fue sustituido por la migración versionada
-- `20260907084525_multiple_group_admins.sql`. La autorización vigente usa
-- `group_members.role`, conserva `groups.created_by` como creador inmutable y
-- permite eliminar el grupo exclusivamente a ese creador.
