#!/usr/bin/env python3
"""Build the word-game migration from RLA-ES v2.9's es_ES Hunspell files.

Usage: PYTHONPATH=/path/to/spylls python3 scripts/generate-word-game-es-es.py \
  /path/to/es_ES.oxt supabase/migrations/<new-migration>.sql
"""

import hashlib
import re
import sys
import tempfile
import unicodedata
import zipfile
from pathlib import Path

from spylls.hunspell.dictionary import Dictionary

EXPECTED_SHA256 = "3eea87836b24b6004aa1ee6fd285b6c71774b0996aec70d096d75d5526efb4ac"
SOURCE = "https://github.com/sbosio/rla-es/releases/tag/v2.9"
LETTERS = re.compile(r"^[A-ZÑ]{4,6}$")


def normalize(value):
    # Keep Ñ distinct while removing vowel accents and diaereses, as the game does.
    value = value.upper().replace("Ñ", "\ue000")
    value = "".join(char for char in unicodedata.normalize("NFD", value) if unicodedata.category(char) != "Mn")
    return value.replace("\ue000", "Ñ")


def forms(word, aff):
    if (aff.FORBIDDENWORD and aff.FORBIDDENWORD in word.flags) or (aff.ONLYINCOMPOUND and aff.ONLYINCOMPOUND in word.flags):
        return
    if not (aff.NEEDAFFIX and aff.NEEDAFFIX in word.flags):
        yield word.stem
    suffixes = [rule for flag in word.flags for rule in aff.SFX.get(flag, []) if rule.cond_regexp.search(word.stem)]
    prefixes = [rule for flag in word.flags for rule in aff.PFX.get(flag, []) if rule.cond_regexp.search(word.stem)]
    for suffix in suffixes:
        root = word.stem[:-len(suffix.strip)] if suffix.strip else word.stem
        suffixed = root + suffix.add
        if not (aff.NEEDAFFIX and aff.NEEDAFFIX in suffix.flags):
            yield suffixed
        for flag in suffix.flags:
            for following in aff.SFX.get(flag, []):
                if following.cond_regexp.search(suffixed):
                    root = suffixed[:-len(following.strip)] if following.strip else suffixed
                    yield root + following.add
    for prefix in prefixes:
        prefixed = prefix.add + word.stem[len(prefix.strip):]
        if not (aff.NEEDAFFIX and aff.NEEDAFFIX in prefix.flags):
            yield prefixed
        if prefix.crossproduct:
            extra = [rule for flag in prefix.flags for rule in aff.SFX.get(flag, [])
                     if rule.crossproduct and rule not in suffixes and rule.cond_regexp.search(prefixed)]
            for suffix in suffixes + extra:
                if not suffix.crossproduct:
                    continue
                root = prefixed[:-len(suffix.strip)] if suffix.strip else prefixed
                suffixed = root + suffix.add
                yield suffixed
                for flag in suffix.flags:
                    for following in aff.SFX.get(flag, []):
                        if following.crossproduct and following.cond_regexp.search(suffixed):
                            root = suffixed[:-len(following.strip)] if following.strip else suffixed
                            yield root + following.add


def main():
    asset, destination = map(Path, sys.argv[1:3])
    actual_hash = hashlib.sha256(asset.read_bytes()).hexdigest()
    if EXPECTED_SHA256 and actual_hash != EXPECTED_SHA256:
        raise SystemExit(f"Unexpected es_ES release SHA-256: {actual_hash}")
    with tempfile.TemporaryDirectory() as directory, zipfile.ZipFile(asset) as archive:
        for name in ("es_ES.aff", "es_ES.dic"):
            Path(directory, name).write_bytes(archive.read(name))
        dictionary = Dictionary.from_files(str(Path(directory, "es_ES")))
        words = set()
        for entry in dictionary.dic.words:
            # The game is about Spanish words, not personal names, places or acronyms.
            if not entry.stem or not entry.stem[0].islower():
                continue
            for form in forms(entry, dictionary.aff):
                normalized = normalize(form)
                if LETTERS.fullmatch(normalized):
                    words.add(normalized)
    for required in ("PANES", "HUEVOS", "UVAS", "TAZAS", "PECES"):
        if required not in words:
            raise SystemExit(f"Missing expected plural: {required}")
    sorted_words = sorted(words)
    sql = [
        "-- RLA-ES v2.9, es_ES; generated by scripts/generate-word-game-es-es.py.\n",
        f"-- Source: {SOURCE}\n-- SHA-256 (es_ES.oxt): {actual_hash}\n",
        "-- Original authors: Santiago Bosio and RLA-ES contributors. License: GPL-3.0+ OR LGPL-3.0+ OR MPL-1.1+.\n",
        "-- License notice: https://github.com/sbosio/rla-es/blob/master/LICENSE.md\n",
        "-- Existing games/guesses keep their FK rows; only the active vocabulary changes.\n",
        "create temporary table word_game_import(word text primary key);\n",
    ]
    for offset in range(0, len(sorted_words), 1500):
        chunk = " ".join(sorted_words[offset:offset + 1500])
        sql.append(f"insert into word_game_import(word) select unnest(string_to_array('{chunk}', ' '));\n")
    sql.extend([
        "update private.word_dictionary set enabled = false where language = 'es' and enabled;\n",
        "insert into private.word_dictionary(language, word, enabled)\n",
        "select 'es', word, true from word_game_import\n",
        "on conflict (language, word) do update set enabled = true;\n",
        "-- An in-progress old game can still be solved even if its word is absent from RLA-ES.\n",
    ])
    previous = Path("supabase/migrations/20260916192534_word_game_scoring_v2.sql").read_text(encoding="utf-8")
    start = previous.index("create or replace function private.word_submit(")
    end = previous.index("\n$$;", start) + len("\n$$;")
    submit = previous[start:end]
    old_check = """or not exists (
    select 1 from private.word_dictionary where language = 'es' and word = normalized and enabled
  ) then"""
    new_check = """or (normalized <> g.solution and not exists (
    select 1 from private.word_dictionary where language = 'es' and word = normalized and enabled
  )) then"""
    if submit.count(old_check) != 1:
        raise SystemExit("Cannot locate the expected validation in word_submit")
    sql.append(submit.replace(old_check, new_check) + "\n")
    sql.append("drop table word_game_import;\n")
    destination.write_text("".join(sql), encoding="utf-8")
    print(f"Generated {destination}: {len(sorted_words)} words; SHA-256 {actual_hash}")


if __name__ == "__main__":
    main()
