-- Historico de precio por zona/centro de entrega.
--
-- Consum y Plusfresc publican un surtido y precio distinto segun la ubicacion.
-- Sus JSONB en *_products sirven para pintar el catalogo, pero no para conocer
-- el precio anterior de una zona concreta. Esta migracion normaliza el precio
-- efectivo por producto+ubicacion y conserva cada variacion como un evento.
--
-- Ejecutar DESPUES de consum_regions.sql y plusfresc_catalog.sql, y ANTES del
-- siguiente sync multi-zona. El primer llenado no genera eventos.

create table if not exists public.catalog_location_prices (
  id                  text primary key, -- ${store}:${location_id}:${product_id}; compatible con markStale
  store               text not null check (store in ('consum', 'plusfresc')),
  product_id          text not null,
  location_id         text not null, -- X-TOL-ZONE (Consum) o center id (Plusfresc)
  unit_price          numeric,
  price_per_unit      numeric,
  price_per_unit_unit text,
  available           boolean not null default true,
  published           boolean not null default true,
  synced_at           timestamptz not null default now(),
  unique (store, product_id, location_id)
);

create table if not exists public.catalog_location_price_changes (
  id               bigint generated by default as identity primary key,
  store            text not null check (store in ('consum', 'plusfresc')),
  product_id       text not null,
  location_id      text not null,
  prev_unit_price  numeric not null,
  new_unit_price   numeric not null,
  price_delta_pct  numeric not null,
  changed_at       timestamptz not null default now()
);

create index if not exists catalog_location_prices_lookup_idx
  on public.catalog_location_prices (store, location_id, product_id)
  where published;
create index if not exists catalog_location_price_changes_feed_idx
  on public.catalog_location_price_changes (store, location_id, changed_at desc);

-- Los UPSERTs actualizan siempre synced_at. Solo registrar un evento cuando
-- cambia un precio valido; INSERT es el primer llenado y no dispara este trigger.
create or replace function public.catalog_track_location_price_change()
returns trigger
language plpgsql
as $$
begin
  if new.unit_price is distinct from old.unit_price
     and old.unit_price is not null and old.unit_price > 0
     and new.unit_price is not null then
    insert into public.catalog_location_price_changes (
      store, product_id, location_id, prev_unit_price, new_unit_price,
      price_delta_pct, changed_at
    ) values (
      new.store, new.product_id, new.location_id, old.unit_price, new.unit_price,
      round((new.unit_price - old.unit_price) / old.unit_price * 100, 1), now()
    );
  end if;
  return new;
end;
$$;

drop trigger if exists track_location_price_change on public.catalog_location_prices;
create trigger track_location_price_change
  after update of unit_price on public.catalog_location_prices
  for each row execute function public.catalog_track_location_price_change();

-- Catalogo publico de solo lectura; los syncs escriben con service_role.
alter table public.catalog_location_prices enable row level security;
alter table public.catalog_location_price_changes enable row level security;

grant select on public.catalog_location_prices, public.catalog_location_price_changes
  to anon, authenticated;

drop policy if exists "location prices read" on public.catalog_location_prices;
create policy "location prices read"
on public.catalog_location_prices for select to anon, authenticated using (true);

drop policy if exists "location price changes read" on public.catalog_location_price_changes;
create policy "location price changes read"
on public.catalog_location_price_changes for select to anon, authenticated using (true);

comment on table public.catalog_location_prices is
  'Precio efectivo actual por producto y zona/centro de entrega.';
comment on table public.catalog_location_price_changes is
  'Historico inmutable de cambios de precio por producto y zona/centro.';
